%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /scratch/user/griffith/eigenplots2/online_ratings.xls
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 02-Apr-2020 13:40:34
function onlineratings=gen_onlineratings()
    %% Setup the Import Options
    opts = spreadsheetImportOptions("NumVariables", 1);

    % Specify sheet and range
    opts.Sheet = "Sheet1";
    opts.DataRange = "H2:H41";

    % Specify column names and types
    opts.VariableNames = "VarName8";
    opts.VariableTypes = "string";
    opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
    opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

    % Import the data
    onlineratings = readtable("/scratch/user/griffith/eigenplots/online_ratings.xls", opts, "UseExcel", false);

    %% Convert to output type
    onlineratings = table2array(onlineratings);

    %% Clear temporary variables
    clear  opts

    %% Getting legend to work
    %h=findobj(gca,'Type','line')
end
